# Generated by Django 5.2.4 on 2026-01-17 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='takenquiz',
            name='correct_answers',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='takenquiz',
            name='total_questions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
